export const news = [
    {
    "News":"How A Farmer From Nashik Grew 195 Quintal Onion",
    "Img url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3AIRIDnzfpjdxQ3JGjwObyRZrN24f9FNbAA&usqp=CAU",
    "Description":"Modern farming methods have often proven effective and have delivered outstanding results. A farmer from Nashik, stands testimony to the wonders modern farming techniques can do. Here’s how Mr. Balu Darade grew a whopping 195 quintal onion –NABARD’s golden initiative.The National Bank for Agriculture and Rural Development (NABARD) initiated a noble program where it trained the farmers for modern farming techniques. Mr. Balu Darade participated in this program as he wished to yield more than 100 quintal, his average produce.Goodbye to traditional technique.The traditional method of sowing on flat beds was replaced by raised beds. Following are the advantages of raised bed sowing –Water can be supplied through drip irrigation.The temperature can be maintained in raised bed sowing Spacing can be easily maintained Drip irrigation Raised bed sowing allowed the water to be supplied through drip irrigation, a method which has its own advantages –Drip irrigation reduces water wastage.Evaporation is minimal and the consumption is lowered.Fertilisers can be used via the dripping system.The land between the plant rows remain dry and unwanted plant growth is prevented.Apart from the good yield, the new techniques helped him save labour cost for irrigation, fertiliser application and removal of weeds. And guess what, he saved around Rs. 6,000 per acre.If you too want to learn about modern farming techniques and get valuable tips, visit https://mahadhan.co.in/crop-portfolio/onion-farming/"
    },
    {
    "News":"7 Tips To Get The Best Wheat Produce",
    "Img url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiaXfADonPxnUNAfZOKJXll76LGFN8CV6P4Q&usqp=CAU ",
    "Description":"Wheat is one of the most important food crops in the world and wheat farming requires proper planning to produce a high yield.Most farmers prefer growing wheat in winter when the average temperature is between 18-24 degree Celsius. However, farmers who reside in extremely cold climates prefer the spring season as it allows enough sunlight for the wheat crop to flourish.Seven tips for successful wheat seeding and farming for maximum yield:1: Pick a dry area for cultivation: Wheat is both a spring and winter crop, and utilizes at least 8 hours of sun on a daily basis. Therefore, avoid picking a site that’s too shady and doesn’t allow enough sunlight.2: Prepare the land well in advance: Growing wheat requires prepping the soil for strong root growth. Till your soil to a depth of at least 15 cm, and make sure that it’s even.3: Spread the wheat seeds in a semi-circular motion: You can always use a seed spreader too, as long as it spreads the seeds at approximately one seed per 2.5 sq. cm.4: Use phosphorus, nitrogen & Potassium fertilization: Phosphorus and nitrogen collectively help develop strong roots which will help the wheat crop survive winter. Optimum dose of Mahadhan 12:32:16 (75 Kg/ac) can help wheat growers to get more yield. In addition to this, application of Mahadhan Bensulf (10 kg/ac) & Mahadhan Zinc sulphate (10 Kg/ac) can further help wheat farmers to get quality oriented higher yield fetching better market price. However, note that excessive nitrogen fertilization can have adverse effects on the crop’s sustenance.5: Water right after planting the seeds: Winter wheat crops require water as soon as the seeds are planted. It is imperative to keep the entire planting area moist until the plant begins to develop. Then on, follow a strict irrigation schedule.6: Follow an irrigation schedule: For maximum yield of wheat crop, an irrigation schedule of 6 stages post sowing is highly recommended:1st irrigation – 3-4 weeks 2nd irrigation – 40-45 days 3rd irrigation – 60-65 days 4th irrigation – 80-85 days 5th irrigation – 100-105 days 6th irrigation – 105-120 days ,7: Use pesticides and insecticides as necessary: Wheat crop is not averse to slugs and insects that can wreak havoc on the plantation, especially when the wheat is still very short. Use chemicals like Chlorpyrifos and acetamiprid in such a case that effectively manage the insects. Now that you know how to obtain the best wheat produce, why not explore Mahadhan's extensive range of high-quality fertilisers that ensure maximum yield of your crops"
    },
    {
    "News":"Potato – Diseases And Symptoms",
    "Img url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCmNPkwEn_n15fdTwwqMcXsaQ5kng_KXKjGg&usqp=CAU",
    "Description":"Potatoes are one of the most common and important food sources on the planet. While there are several benefits of growing potatoes, it’s important to know that there are many diseases that the tubers catch. So, if you are growing potatoes this season, here are the types of potato diseases, potato disease control, and their management you should know Late blight: Late blight damages leaves, stems and tubers (potatoes). Affected leaves appear blistered as if scalded by hot water and eventually rot and dry out. To treat late blight, plant resistant cultivators are used. You should also use soaker hoses to give plants time to dry out during the day as the disease develops in humid conditions.Bacterial Wilt: In this disease, the infected plant first begins to wilt and spreads to all parts of the plant. Leaves become yellow at their bases. Then the whole plant wilts and dies. Bacterial wilt has no cure. However, it can be controlled using methods of crop rotation, selecting suitable sites, using certified seeds and uprooting diseased plants. Blackheart disorder: Blackheart occurs primarily in storage when the tubers do not receive enough oxygen. The potatoes develop acute oxygen deficiency that results in blackening at the center. The tissue dies from the inside out and turns jet black. The disease occurs either due to low temperature in confined storage or high field soil temperatures. Blackheart can be prevented through good ventilation in storage, avoiding flooded areas and extreme temperatures.To get more information and valuable tips on farming, visit https://mahadhan.co.in/"
    },
    {
    "News":"5 Mistakes Farmers Should Avoid While Applying Fertilisers",
    "Img url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtWNTZdCgq5otrCa0gn3K5EHlVWPIgaT3nRA&usqp=CAU",
    "Description":"Here are five basic mistakes farmers should watch out for to ensure a successful harvest of crops,Imbalanced Nutrition: Plants require balanced nutrition to grow to their full potential.This consists of at least 13 essential nutrients in different quantities. Farmers normally consider only NPK fertiliser application, ignoring the importance of other essential nutrients and micronutrients. This often results in reduced yield and an average-quality crop.Fertiliser application without soil testing: Soil testing is crucial before you choose/apply fertilisers. You can then choose the right fertilisers based on the soil test report. It is essential to provide deficient nutrients through fertilisers if you want a high yield.Too much fertiliser: A common assumption among farmers regarding fertiliser application is that a higher dose of fertiliser will give a better yield, which is not true. Fertiliser overdose adversely affects the crop, soil, and environment. Irreversible damage can be caused due to salinity build up or due to the toxicity of specific elements.Wrong timing: Failing to apply the right fertiliser quantity at the right time is a common mistake that leads to reduced yield and damaged crops.Incorrect fertiliser placements: Fertiliser placement is an integral part of efficient crop management. Correct placement often improves nutrient absorption by plants, and consequently boosts yields. Inorganic fertilisers can be applied manually or with application equipment. When applied manually, it is essential to distribute the fertilisers uniformly. Application equipment needs proper adjustment to ensure uniform spreading. Broadcast fertilisers should be incorporated after application to enhance effectiveness and to avoid evaporation. With banding or spot application, take care that no fertiliser is placed too close to either the seed or the germinating plant, to avoid damage to the seedling or roots."
    },
    
    
    
    {
    "News":"How To Get The Best Soybean Produce",
    "Img url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXdTCLqtvBS7JQmCaWbxnbnbDs719gYS73UQ&usqp=CAU",
    "Description":"Soybean is one of the most important crops in India. If you follow the right procedure and modern farming techniques, this crop will surely give you maximum returns in just 4 months. Mr. Prashant Patil from Sangli has produced a whopping 28 quintal per acre of soybean. Here are a few important farming tips from Mr. Patil that will help you get a good soybean produce .Know the type of your soil: Soybean requires well-drained and fertile loamy soil. In order to prevent damage from water logging, it is recommended to have proper drainage system during the rainy season.Examine the seeds well in advance: Purchase seeds a few days before sowing them. This will help you in analysing the germination capability of the seeds. The recommended germination for soybean is around 70%.Seed rate: Ideally, the average seed rate is around 16 Kg per acre. However it varies depending on various factors such as seed size, germination, percentage and sowing time.Seed treatment: It is advisable to use 250 gm rhizobium and 250 gm PSB per 15 Kg soybean seeds. Caution: after adding rhizobium and PSB, don’t rub the seeds by hands as it can damage the coating and invite fungal diseases.Fertiliser management: Sulphur and Phosphate are two of the most essential nutrients for Soybean. To fulfill this requirement it is recommended to use Single Super Phosphate and Bensulf. Mr Prashant Patil used 10 Kg Mahadhan Bensulf per acre and got excellent results.Weed control: The spraying of weedicides must be done within 2 days of sowing. Carry out manual weeding after 2 weeks.Pest and disease control: Spray pesticides within 10 days to protect your crop from pests and diseases. In addition, it is advisable to use Mahadhan 19:19:19. 12:61:00 and micro nutrients to provide the essential nutrition to your crop during its growing period.Drip irrigation: In case of less rainfall, it is recommended to use sprinkler irrigation. This has resulted in a good output for Mr Patil and has increased the produce by around 25%."
    },
    
    
    
    
    {
    "News":"Tips On Increasing Sugarcane Yield",
    "Img url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_w2HjTY54YGwKwz1rJI_bU3WrGbytlaALlQ&usqp=CAU",
    "Description":"Mr. Sanjeev Mane from Sangli was awarded Krushi Bhushan for his astounding work in farming and yielding a whopping 100 tonne sugarcane per acre. How did he achieve this feat? Here’s what he did –Drip irrigation: It is a myth that sugarcane crop requires a lot of water. Implementing drip irrigation system can further reduce the wastage of water. According to Mr. Mane, where traditional methods used 1 Crore litres of water, drip irrigation needed just 40 Lac litres of water. Effective water management helps in getting good output as well. To avoid additional maintenance costs, Mr. Mane also suggests using sub-surface drip irrigation instead of lateral drip irrigation. Apart from this, what Mr. Mane a few basic things in mind –   To know the soil test values by soil testing  prior to planting is key to fertiliser management in sugarcane.Soil: Sugarcane can grow on a variety of soils including loams, clayey loams, black cotton soils, brown or reddish loams and even laterites. In fact, sugarcane can tolerate any kind of soil that can retain moisture. But deep rich loamy soils are ideal for its growth.Essential nutrients: Nitrogen, calcium and phosphorus are the most important nutrients required for a good produce of sugarcane. Optimum nutrition can help improve the sugarcane yield.Climate: It requires hot and humid climate with average temperature of 21°-27°C and 75cm -150cm rainfall.Fertilisers: Sugarcane requires a heavy dose of fertiliser as it exhausts the fertility of the soil quickly.Intercropping: Sugarcane intercropping with short duration vegetable crops like Cabbage & cauliflower were found to be highly beneficial for the farmers. In areas of adequate irrigation, sowing one row of soybean or black gram helps to increase the soil fertility and sugarcane yield."
    }
]